image: docker:latest

build-docker:
  stage: build

  services:
    - docker:dind

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$DOCKERHUB_REGISTRY_USER" -p "$DOCKERHUB_REGISTRY_PASSWORD" $DOCKERHUB_REGISTRY

  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" .
    - docker tag "$CI_REGISTRY_IMAGE:latest" "$DOCKERHUB_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:latest"
    - docker push "$DOCKERHUB_REGISTRY_IMAGE:latest"

  after_script:
    - docker logout $CI_REGISTRY
    - docker logout $DOCKERHUB_REGISTRY

  only:
    - master
